#!/usr/bin/env python3
import pathlib
import sys


def main():
	if len(sys.argv) != 5:
		print("usage: embed_binary.py <input> <output> <namespace> <symbol>", file=sys.stderr)
		return 2

	input_path = pathlib.Path(sys.argv[1])
	output_path = pathlib.Path(sys.argv[2])
	namespace = sys.argv[3]
	symbol = sys.argv[4]
	data = input_path.read_bytes()

	output_path.parent.mkdir(parents=True, exist_ok=True)
	with output_path.open("w", newline="\n") as out:
		out.write("/* Generated by builds/cmake/embed_binary.py. */\n")
		out.write("#include <cstddef>\n")
		out.write("#include <cstdint>\n\n")
		out.write(f"namespace {namespace} {{\n")
		out.write(f"extern const uint8_t {symbol}[] = {{")

		for index, byte in enumerate(data):
			if index % 12 == 0:
				out.write("\n\t")
			out.write(f"0x{byte:02x},")

		out.write("\n};\n")
		out.write(f"extern const std::size_t {symbol}_size = sizeof({symbol});\n")
		out.write("}\n")

	return 0


if __name__ == "__main__":
	raise SystemExit(main())
